blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.post_list, name='post_list'),
    path('blog/<int:year>/<int:month>/<int:day>/<slug:post>', views.get_post_details, name='get_post_details'),
    path('blog/comment/<int:post_id>/new', views.add_comment, name='add_comment'),
    path('blog/comment/<int:comment_id>/delete', views.delete_comment, name='delete_comment'),
    path('blog/comment/<int:comment_id>/edit', views.edit_comment, name='edit_comment'),
    path('blog/comment-form/<int:post_id>', views.comment_form, name='comment_form'),
    path('blog/<int:post_id>/share/', views.share_post, name='share_post'),
    path('blog/post/new', views.post_create_view, name='new_post'),
    path('blog/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('blog/<int:post_id>/update/', views.update_post, name='update_post'),
    path('blog/search', views.search_post, name='search_posts'),
    path('blog/post/top/', views.top_posts_view, name='top_posts'),
]

blogPost/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('social_django.urls', namespace='social')),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.conf import settings


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        BANNED = 'BN', 'Banned'
        DELETED = 'DL', 'Deleted'

    title = models.CharField(max_length=200, verbose_name='Заголовок')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    year = models.IntegerField(default=None, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(max_length=200, unique=True, unique_for_date="published")
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Автор")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:get_post_details',
            args=[self.published.year, self.published.month, self.published.day, self.slug]
        )

    class Meta:
        ordering = ['-published']
        # verbose_name = 'Объявление'
        # verbose_name_plural = 'Объявления'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField(verbose_name='comment area')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return f'Written by: {self.author} about: {self.post}'

blog/forms.py
from django import forms
from blog.models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

    author = forms.IntegerField(widget=forms.HiddenInput(), required=False)


class EmailForm(forms.Form):
    sender = forms.CharField(max_length=50)
    email_from = forms.EmailField()
    email_to = forms.EmailField()


class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'status',)
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Name of the Poem'}),
            'body': forms.Textarea(attrs={'rows': 10, 'cols': 100}),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }


class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'status']

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.text import slugify
from django.views.decorators.http import require_POST
from blog.models import Post, Comment
from blog.forms import CommentForm, EmailForm, NewPostForm
from django.core.mail import send_mail
from unidecode import unidecode
from blog.forms import EditPostForm
from django.db.models import Q
from blog.utils import r, get_top_posts, update_post_views

from django.core.paginator import Paginator
from django.http import HttpResponseForbidden, HttpResponse
from django.template.loader import render_to_string

# def post_list(request):
#     all_posts = Post.objects.all()
#     paginator = Paginator(all_posts, 3)
#     page_number = request.GET.get('page', 1)
#     posts = paginator.get_page(page_number)
#     return render(
#         request,
#         'blog/post/post_get_list.html',
#         {'posts': posts, 'all_posts': all_posts}
#     )


'''integrating partial reloading via HTMX using paginator --> '''


def post_list(request):
    all_posts = Post.objects.all()
    paginator = Paginator(all_posts, 2)
    page_number = request.GET.get('page', 1)
    posts = paginator.get_page(page_number)

    if request.headers.get('HX-Request'):
        # return HttpResponse(render_to_string('endless_post_get_list.html',
        #                                      {'posts': posts})
        #                     )
        return HttpResponse(render_to_string('partial_post_get_list.html',
                                             {'posts': posts})
                            )

    return render(
        request,
        'blog/post/post_get_list.html',
        {'posts': posts})


#################################################################################
def get_post_details(request, year, month, day, post):
    post = get_object_or_404(Post, published__year=year, published__month=month, published__day=day, slug=post, )
    comments = post.comments.filter(active=True)

    try:
        # post_key = f'post:{post.id}:views'
        post_key = post.id
        # update_post_rating(post.id)
        update_post_views(post.id, 1)
        total_views = int(r.get(post_key))

    except (ConnectionError, TimeoutError):
        total_views = 0

    form = CommentForm()

    return render(
        request,
        'blog/post/post_get_details.html',
        {'post': post, 'comments': comments, 'form': form, 'total_views': total_views}
    )


@login_required
def post_create_view(request):
    if request.method == 'POST':
        form = NewPostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.slug = slugify(unidecode(post.title))
            post.save()
            return redirect('blog:post_list')
    else:
        form = NewPostForm()
    return render(request,
                  'blog/post/post_create.html',
                  {'form': form, })


def update_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return HttpResponseForbidden("You are not allowed to edit this post.")
    if request.method == "POST":
        form = EditPostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:get_post_details',
                            year=post.published.year,
                            month=post.published.month,
                            day=post.published.day,
                            post=post.slug)
    else:
        form = EditPostForm(instance=post)
    return render(request, 'blog/post/post_update.html', {'form': form, 'post': post})


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, author=request.user)
    if request.method == 'POST':
        post.delete()
        return redirect('accounts:profile_view')
    return render(request, 'blog/post/post_delete_confirm.html', {'post': post})


# ########################### MESSAGE BROKER ##########################################

@login_required()
def share_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    sent = False
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())  # create link of absolute type (https://...)
            # subject = f"{cd['sender']} recommends you check out {post.title}"
            subject = 'Hello World {}'.format(post.get_absolute_url().title())
            print('print:', subject)
            message = f"Check out the post '{post.title}' at the following link:\n{post_url}\n"
            send_mail(
                subject=subject,
                message=message,
                # from_email=[cd['email_from']],  # extract from User object !!!
                from_email='sender@test.com',
                recipient_list=[cd['email_to']],
            )
            sent = True
    else:  # which would be a GET request
        form = EmailForm()
    return render(
        request,
        'blog/post/post_share.html',
        {'post': post, 'form': form, 'sent': sent}
    )


# ############################# SEARCH ###########################################
def search_post(request):
    query = request.GET.get('q')
    results = []
    if query:
        results = Post.objects.filter(Q(title__icontains=query) | Q(body__icontains=query)).order_by('-published')
    return render(request,
                  'blog/post/post_search_results.html',
                  {'results': results, 'query': query})


# ################################# REDIS as CACHE ########################################
def top_posts_view(request):
    top_posts = get_top_posts()
    return render(request, 'blog/post/post_top_10.html', {'top_posts': top_posts})


# ################################## COMMENT #########################################
# COMMENT

@login_required
def comment_form(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    return render(request,
                  'blog/post/includes/comment_form.html',
                  {'post': post, 'form': form})


@login_required
@require_POST
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comment = None
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.author = request.user
        comment.save()
    return render(
        request,
        'blog/post/comment_create_confirm.html',
        {'post': post, 'comment': comment, 'form': form}
    )


@login_required
def edit_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.author != request.user:
        return redirect('blog:posts_list')
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect(comment.post.get_absolute_url())
    else:
        form = CommentForm(instance=comment)
    return render(request,
                  'blog/post/comment_edit.html',
                  {'form': form, 'comment': comment})


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.author != request.user:
        return redirect('blog:post_list')
    if request.method == 'POST':
        comment.delete()
        return redirect(comment.post.get_absolute_url())
    return render(request,
                  'blog/post/comment_delete_confirm.html',
                  {'comment': comment})

blog/templates/blog/post/comment_create_confirm.html
{% extends 'base.html' %}
{% load static %}
{% block head %}<link rel="stylesheet" href="{% static '/blog/css/style.css' %}">{% endblock %}
{% block title %} comment.html {% endblock %}

{% block content %}
    <a href="{% url 'blog:get_post_details' year=post.published.year month=post.published.month day=post.published.day post=post.slug %}">
        <h4>back to post</h4>
    </a>

    {% if comment %}
        <p>You Comment Successfully Submitted</p>
    {% else %}
        <p>{% include "blog/post/includes/comment_form.html" %}</p>
    {% endif %}

{% endblock %}

blog/templates/blog/post/comment_delete_confirm.html
{% extends 'base.html' %}

{% block title %} Comment Deletion {% endblock %}

{% block content %}
    <div>
        <h2>Comment Deletion</h2>
        <p>Are you sure you want to delete this comment?</p>
        <blockquote>
            {{ comment.body }}
        </blockquote>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" value="Yes, please">
            <a href="{{ comment.post.get_absolute_url }}">No, go back!</a>
        </form>
    </div>
{% endblock %}

blog/templates/blog/post/comment_edit.html
{% extends 'base.html' %}

{% block title %} comment_edit.html {% endblock %}

{% block content %}

    <h2>Edit Comment</h2>

    <hr>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
        <a href="{{ comment.post.get_absolute_url }}">Cancel</a>
    </form>

{% endblock %}

blog/templates/blog/post/post_create.html
{% extends 'base.html' %}

{% block content %}
    <h2>New Post</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Publish</button>
    </form>
{% endblock %}

blog/templates/blog/post/post_delete_confirm.html
{% extends 'base.html' %}

{% block title %} Post Deletion {% endblock %}

{% block content %}
    <div>
        <h2>Post Deletion</h2>
        <p>Are you sure you want to delete this post?</p>
        <blockquote>
            {{ post.body }}
        </blockquote>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" value="Yes, please">
            <a href="{{ post.get_absolute_url }}">No, go back!</a>
        </form>
    </div>
{% endblock %}

blog/templates/blog/post/post_get_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %} post_details.html {% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock %}

{% block content %}

    {% if user.is_authenticated %}
        <a href="{% url 'blog:comment_form' post.id %}">comment</a>
        <br>
        <a href="{% url 'blog:share_post' post.id %}">share</a>
        <br>
        <a href="{% url 'blog:top_posts' %}">rating</a>
    {% else %}
        <p>Please Sign In to Leave a Comment</p>
    {% endif %}


    <div id="content-post">
        <p>post views: {{ total_views }}</p>
        <h1>{{ post }}</h1>
        <h4>{{ post.body|safe }}</h4>

        {% for comment in comments %}
            <div class="comment">
                <hr>
                <p>{{ comment.body }}</p>
                <p style="font-size: x-small">by {{ comment.author.username }} </p>
            </div>
            {% if comment.author == user %}
                <button><a href="{% url 'blog:edit_comment' comment.id %}">Edit</a></button>
                <button><a href="{% url 'blog:delete_comment' comment.id %}">Delete</a></button>
            {% endif %}
            <div>{% empty %}</div>
            <hr>
            <p>there are no comments for this post</p>
        {% endfor %}
    </div>

{% endblock %}

blog/templates/blog/post/post_get_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} post_get_list.html {% endblock %}

{% block content %}

    {#########    Partial Reloading of the Page <div> ################}
    <div id="posts-container">
        {% include 'partial_post_get_list.html' with posts=posts %}
    </div>


    {#########    Endless Scrolling Reloading <div> ################}
    {#    <div id="posts-container">#}
    {#        {% include 'endless_post_get_list.html' %}#}
    {#    </div>#}

{% endblock %}

blog/templates/blog/post/post_search_results.html
{% extends 'base.html' %}

{% block content %}

    <div class="flex-container">

        <h1>Search results : " {{ query }} "</h1>

        {% if results %}
            <ul>
                {% for post in results %}
                    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}

    </div>
{% endblock %}

blog/templates/blog/post/post_share.html
{% extends 'base.html' %}

{% block title %} share_post.html {% endblock %}

{% block content %}

    {% if sent %}
        <h3>Your email was successfully sent</h3>
        <a href={% url 'blog:post_list' %}>back to list of posts</a>
    {% else %}
        <h3>Share by email</h3>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="share">
        </form>
    {% endif %}

{% endblock %}

blog/templates/blog/post/post_top_10.html
{% extends 'base.html' %}

{% block title %} post_top_10.html {% endblock %}

{% block content %}

    <h2>Top Posts:</h2>
    <ul>
        {% for post, views in top_posts %}
            <li><a href="{{ post.get_absolute_url }}">{{ post.title }} has {{ views }} views</a></li>
        {% endfor %}
    </ul>

{% endblock %}

blog/templates/blog/post/post_update.html
{% extends 'base.html' %}

{% block title %} post_update.html {% endblock %}


{% block content %}
    <div id="edit-post-form">
        <h1>Update Post</h1>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save Changes</button>
            <a href="{{ post.get_absolute_url }}">Cancel</a>
        </form>
    </div>
{% endblock %}