accounts/urls.py
from accounts import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_view, name='register_view'),
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('profile/', views.profile_view, name='profile_view'),
    path('profile/edit', views.profile_edit_view, name='profile_edit_view'),
    path('login/telegram/complete/', views.telegram_login_complete, name='telegram_login_complete'),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.post_list, name='post_list'),
    path('blog/<int:year>/<int:month>/<int:day>/<slug:post>', views.get_post_details, name='get_post_details'),
    path('blog/comment/<int:post_id>/new', views.add_comment, name='add_comment'),
    path('blog/comment/<int:comment_id>/delete', views.delete_comment, name='delete_comment'),
    path('blog/comment/<int:comment_id>/edit', views.edit_comment, name='edit_comment'),
    path('blog/comment-form/<int:post_id>', views.comment_form, name='comment_form'),
    path('blog/<int:post_id>/share/', views.share_post, name='share_post'),
    path('blog/post/new', views.post_create_view, name='new_post'),
    path('blog/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('blog/<int:post_id>/update/', views.update_post, name='update_post'),
    path('blog/search', views.search_post, name='search_posts'),
    path('blog/post/top/', views.top_posts_view, name='top_posts'),
]

blogPost/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('social_django.urls', namespace='social')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %} {% endblock %} </title>
    <link href="{% static "blog/css/style.css" %}" rel="stylesheet">
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
</head>

<body>
<div id="nav-sidebar">
    <h2><a href="{% url 'blog:post_list' %}">Blog Post</a></h2>

    <ul>
        {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:profile_view' %}">Profile</a></li>
            <Li><a href="{% url 'accounts:profile_edit_view' %}">Edit Profile</a></Li>
            <Li><a href="{% url 'blog:new_post' %}">New Post</a></Li>
            <Li><a href="{% url 'accounts:logout_view' %}">Exit</a></Li>
        {% else %}
            <li><a href="{% url 'accounts:register_view' %}">Register</a></li>
            <li><a href="{% url 'accounts:login_view' %}">Login</a></li>
        {% endif %}
    </ul>

    {% if user.is_authenticated %}
        <div>
            <form action="{% url 'blog:search_posts' %}" method="GET">
                <label>
                    <input type="text" name="q" placeholder="search">
                </label>
                <button type="submit">search</button>
            </form>
        </div>
    {% endif %}

</div>

<div id="content">
    <h1>Poetry Of Eighteenth Century</h1>
    {% block content %} {% endblock %}
</div>
</body>
<footer>
    <hr>
    <div style="margin: 33px 0 0 33px;">
        <p>&copy; 2024 "LennyProDuckT"</p>
        <p>All rights reserved</p>
    </div>
</footer>
</html>